GET http://localhost:8080/

###
GET http://localhost:8080/api/users

###
GET http://localhost:8080/api/users/13

###
GET http://localhost:8080/api/users/4/posts


### Valid user creation
POST http://localhost:8080/api/users/
content-type: application/json

{
    "name": "Papa Smurf"
}

### User with no name
POST http://localhost:8080/api/users/
content-type: application/json

{
  "color": "red"
}

### User with no body
POST http://localhost:8080/api/users/


### Valid post creation
POST http://localhost:8080/api/users/
content-type: application/json

{
    "name": "Bart Simpson"
}

### Delete a user
DELETE http://localhost:8080/api/users/45

### Valid user update
PUT http://localhost:8080/api/users/13
content-type: application/json

{
    "name": "JarJar Binks"
}